version: "3.9"
services:
  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: megamarket
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    build: ./
    restart: always
    depends_on:
      - db
    ports:
      - 80:8080
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: megamarket

volumes:
  db:
    driver: local