spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

  jpa:
    open-in-view: false

springdoc:
    swagger-ui:
      url: /docs/openapi.yaml