name: Java CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PORT: 5432
          POSTGRES_DB: megamarket
          POSTGRES_USER: megamarket
          POSTGRES_PASSWORD: megamarket
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build application
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: megamarket
          DB_USER: megamarket
          DB_PASS: megamarket
        run: mvn -B package --file pom.xml

  api-test:
    needs: build

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PORT: 5432
          POSTGRES_DB: megamarket
          POSTGRES_USER: megamarket
          POSTGRES_PASSWORD: megamarket
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install newman
        run: npm install -g newman

      - name: Install helper script
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y wget &&
          wget --no-check-certificate -P /tmp/ https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
          chmod a+x /tmp/wait-for-it.sh

      - name: Run application
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: megamarket
          DB_USER: megamarket
          DB_PASS: megamarket
        run: nohup mvn spring-boot:run &

      - name: Waiting for application is up
        run: /tmp/wait-for-it.sh -t 120 localhost:8080 -- echo "application is up"

      - name: Run Postman tests
        run: newman run ./src/test/resources/postman.json -r cli